"""Cruise-ship outbreak analysis. Recomputed each ingest run.

Produces ``data/cruise_analysis.json`` with three blocks:
  - ``current`` — live cruise outbreak figures pulled by cruise_outbreak.get_figures()
  - ``comparison`` — side-by-side metrics: current cluster vs Diamond Princess
  - ``methodology`` — static explainer prose. Tracked in git so any change here
    is reviewable; not regenerated by AI per run.

Cited sources:
- CDC HAN 528 (current cluster): https://www.cdc.gov/han/php/notices/han00528.html
- CDC MMWR 69/12 (Diamond Princess and Grand Princess responses, Feb–Mar 2020):
  https://www.cdc.gov/mmwr/volumes/69/wr/mm6912e3.htm
"""
from __future__ import annotations

import json
from datetime import date, datetime, timezone
from pathlib import Path

from .sources.cruise_outbreak import FALLBACK, get_figures

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"


# Diamond Princess figures, taken from CDC MMWR 69/12 and CDC reports of the period.
# Frozen historical data — does not change. Update only with a primary-source URL.
DIAMOND_PRINCESS = {
    "label": "Diamond Princess (SARS-CoV-2, 2020)",
    "exposed_population": 3711,
    "passengers": 2666,
    "crew": 1045,
    "confirmed_cases": 712,
    "deaths": 14,
    "attack_rate_pct": round(712 / 3711 * 100, 1),
    "cfr_pct": round(14 / 712 * 100, 1),
    "date_range": "2020-02-03 – 2020-02-27 (vessel quarantine period)",
    "source_name": "CDC MMWR 69/12",
    "source_url": "https://www.cdc.gov/mmwr/volumes/69/wr/mm6912e3.htm",
}


METHODOLOGY = {
    "andes_virus_transmission": (
        "Andes virus is the only hantavirus with documented sustained person-to-"
        "person transmission. Family-cluster and healthcare-worker chains have "
        "been reported in Argentina and Chile since the 1990s. Transmission is "
        "believed to occur via respiratory droplet/aerosol during close contact, "
        "with secondary attack rates highest among household contacts of "
        "symptomatic index cases. Most other hantaviruses are strictly zoonotic "
        "(inhalation of aerosolized rodent excreta) and do not transmit between "
        "humans."
    ),
    "covid_transmission": (
        "SARS-CoV-2 transmits efficiently via respiratory aerosols and droplets, "
        "with substantial transmission from pre-symptomatic and asymptomatic "
        "carriers. In closed indoor environments, shared ventilation, prolonged "
        "exposure, and dense occupancy amplify the basic reproduction number."
    ),
    "why_cruise_ships_amplify": (
        "Cruise ships combine prolonged confinement, shared HVAC, communal "
        "dining and entertainment, and a population mixing across ages and "
        "nationalities — the textbook risk profile for respiratory-virus "
        "spread. For a virus with even rare person-to-person capability, a "
        "multi-week ocean voyage creates the time window for incubation chains "
        "to develop and saturate close-contact networks."
    ),
    "key_difference": (
        "SARS-CoV-2 on Diamond Princess produced a ~19% attack rate over 24 "
        "days of cohabitation — characteristic of a highly transmissible "
        "respiratory virus. The 2026 Andes-virus cluster is materially smaller "
        "in attack rate (single-digit percent) but with a far higher case-"
        "fatality rate (~38% historical for HPS vs ~2% for SARS-CoV-2 on "
        "Diamond Princess). The comparison is not 'which is worse' — they "
        "are different shapes of risk."
    ),
}


def write_cruise_analysis() -> None:
    f = get_figures()
    today = date.today()
    total_cases = f.confirmed + f.suspected
    attack_rate_pct = round(total_cases / f.exposed * 100, 2) if f.exposed else None
    cfr_pct = round(f.deaths / total_cases * 100, 1) if total_cases else None
    # Two related metrics. The first advances daily; the second is frozen to
    # whatever the most recent HAN republication date is.
    days_since_departure = (today - FALLBACK["departure_date"]).days
    voyage_duration_to_disclosure = (f.as_of - FALLBACK["departure_date"]).days
    days_since_source_update = (today - f.as_of).days

    current = {
        "label": "2026 Andes-virus cruise cluster",
        "as_of": f.as_of.isoformat(),
        "today": today.isoformat(),
        "days_since_source_update": days_since_source_update,
        "parsed_from_live_source": f.parsed_from_live,
        "confirmed_cases": f.confirmed,
        "suspected_cases": f.suspected,
        "total_cases": total_cases,
        "deaths": f.deaths,
        "exposed_population": f.exposed,
        "passengers": FALLBACK["passengers"],
        "crew": FALLBACK["crew"],
        "departure": {
            "port": FALLBACK["departure_port"],
            "date": FALLBACK["departure_date"].isoformat(),
        },
        "ports_of_call": FALLBACK["ports_of_call"],
        "vessel_met": {
            "location": FALLBACK["met_at"],
            "date": FALLBACK["met_date"].isoformat(),
        },
        "days_since_departure": days_since_departure,
        "voyage_duration_to_disclosure": voyage_duration_to_disclosure,
        "attack_rate_pct": attack_rate_pct,
        "cfr_pct": cfr_pct,
        "virus": "Andes virus",
        "source_name": "CDC HAN 528",
        "source_url": "https://www.cdc.gov/han/php/notices/han00528.html",
    }

    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "current": current,
        "diamond_princess": DIAMOND_PRINCESS,
        "comparison_rows": [
            {
                "metric": "Exposed population",
                "current": f"{f.exposed} ({FALLBACK['passengers']} passengers, {FALLBACK['crew']} crew)",
                "diamond_princess": f"{DIAMOND_PRINCESS['exposed_population']} ({DIAMOND_PRINCESS['passengers']} passengers, {DIAMOND_PRINCESS['crew']} crew)",
            },
            {
                "metric": "Confirmed cases",
                "current": str(f.confirmed),
                "diamond_princess": str(DIAMOND_PRINCESS["confirmed_cases"]),
            },
            {
                "metric": "Suspected / additional",
                "current": str(f.suspected),
                "diamond_princess": "n/a (all PCR-tested)",
            },
            {
                "metric": "Attack rate",
                "current": f"{attack_rate_pct}%" if attack_rate_pct is not None else "—",
                "diamond_princess": f"{DIAMOND_PRINCESS['attack_rate_pct']}%",
            },
            {
                "metric": "Deaths",
                "current": str(f.deaths),
                "diamond_princess": str(DIAMOND_PRINCESS["deaths"]),
            },
            {
                "metric": "Case fatality rate",
                "current": f"{cfr_pct}%" if cfr_pct is not None else "—",
                "diamond_princess": f"{DIAMOND_PRINCESS['cfr_pct']}%",
            },
            {
                "metric": "Voyage duration to public disclosure",
                "current": f"{voyage_duration_to_disclosure} days (departure → HAN as-of)",
                "diamond_princess": "~24 days (quarantine onboard)",
            },
            {
                "metric": "Primary transmission mode",
                "current": "Person-to-person respiratory droplet/aerosol (Andes virus unique)",
                "diamond_princess": "Respiratory aerosol; shared HVAC implicated",
            },
        ],
        "methodology": METHODOLOGY,
        "sources": [
            {"name": "CDC HAN 528", "url": "https://www.cdc.gov/han/php/notices/han00528.html"},
            {"name": "CDC MMWR 69/12 (Diamond Princess)", "url": "https://www.cdc.gov/mmwr/volumes/69/wr/mm6912e3.htm"},
            {"name": "CDC hantavirus situation summary", "url": "https://www.cdc.gov/hantavirus/situation-summary/index.html"},
        ],
    }

    (DATA_DIR / "cruise_analysis.json").write_text(json.dumps(payload, indent=2) + "\n")
